#if !canImport(ObjectiveC)
import XCTest

extension SwiftyCastTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SwiftyCastTests = [
        ("testBridgingCastToUnmanaged", testBridgingCastToUnmanaged),
        ("testBridgingRetainCast", testBridgingRetainCast),
        ("testBridingCastBlocks", testBridingCastBlocks),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SwiftyCastTests.__allTests__SwiftyCastTests),
    ]
}
#endif
