name: Swift Package
on: [push, workflow_dispatch]

jobs:
  build:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]

    name: Build
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Build
      run: |
        swift --version
        swift build -v

  test:
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]

    name: Test
    runs-on: ${{ matrix.os }}
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Test
      run: |
        swift test -v --enable-code-coverage

    - name: Upload Code Coverage
      if: ${{ runner.os == 'macOS' && github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
